/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ObservadorManager;
import Controlador.VentanaControlador;
import Modelo.Dto.CultivoDTO;
import Modelo.Service.CultivoService;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.w3c.dom.events.DocumentEvent;

/**
 *
 * @author isaac
 */
public class GestionCultivo extends javax.swing.JInternalFrame implements TablaObserver {
  private VentanaControlador controlador;
  private CultivoService cultivoService = new CultivoService();
  private DefaultTableModel modeloTabla;
  private TableRowSorter<DefaultTableModel> sorter;
    
  public GestionCultivo(VentanaControlador controlador) {
    initComponents();
    this.controlador = controlador;
    cargarDatosTabla();
    configurarBuscador();

    ObservadorManager.getInstancia().registrarObservador((TablaObserver) this); 
    this.addInternalFrameListener(new InternalFrameAdapter() {
        public void internalFrameClosed(InternalFrameEvent e) {
            ObservadorManager.getInstancia().eliminarObservador((TablaObserver) GestionCultivo.this);
        }
    });
}

@Override
public void actualizarTabla(String tipoEntidad) {
    if (tipoEntidad != null && tipoEntidad.equals("CULTIVO")) {
        cargarDatosTabla();
        filtrar();
    }
}

public void cargarDatosTabla() {
    DefaultTableModel modeloTabla = (DefaultTableModel) Tablacultivo.getModel(); 
    modeloTabla. setRowCount(0); 

    List<CultivoDTO> listaCultivos = controlador.obtenerDatosCultivos();
    for (CultivoDTO cultivo : listaCultivos) {
        Object[] fila = new Object[7]; 
        fila[0] = cultivo.getId(); 
        fila[1] = cultivo.getNombre(); 
        fila[2] = cultivo.getTipo(); 
        fila[3] = cultivo.getAreaSembrada(); 
        fila[4] = cultivo.getEstadoCrecimiento(); 
        fila[5] = cultivo.getFechaSiembra(); 
        fila[6] = cultivo. getFechaCosecha();
        modeloTabla.addRow(fila);
    }

    if (sorter != null) {
        sorter.setModel(modeloTabla);
    }
}

private void configurarBuscador() {
    DefaultTableModel model = (DefaultTableModel) Tablacultivo.getModel();
    sorter = new TableRowSorter<>(model);
    Tablacultivo.setRowSorter(sorter);

    jTextField1.getDocument().addDocumentListener(new DocumentListener() {
        public void insertUpdate(DocumentEvent e) { filtrar(); }
        public void removeUpdate(DocumentEvent e) { filtrar(); }
        public void changedUpdate(DocumentEvent e) { filtrar(); }
public void insertUpdate(javax.swing.event.DocumentEvent e) {
    filtrar();
}

public void removeUpdate(javax.swing.event.DocumentEvent e) {
    filtrar();
}

public void changedUpdate(javax.swing.event.DocumentEvent e) {
    filtrar();
}
     
    });
}

private void filtrar() {
    String text = jTextField1.getText();
    if (text == null || text.trim().isEmpty()) {
        sorter. setRowFilter(null);
    } else {
        try {
            sorter.setRowFilter(RowFilter.regexFilter("(? i)" + java.util.regex.Pattern.quote(text)));
        } catch (PatternSyntaxException ex) {
            sorter.setRowFilter(null);
        }
    }
}
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablacultivo = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.black);
        setResizable(true);
        setTitle("Gestión  de Cultivo");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        Tablacultivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Tipo", "Area sembrada", "Estado Crecimiento", "Siembra", "Cosecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tablacultivo.setColumnSelectionAllowed(true);
        Tablacultivo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tablacultivo);
        Tablacultivo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (Tablacultivo.getColumnModel().getColumnCount() > 0) {
            Tablacultivo.getColumnModel().getColumn(0).setResizable(false);
            Tablacultivo.getColumnModel().getColumn(1).setResizable(false);
            Tablacultivo.getColumnModel().getColumn(2).setResizable(false);
            Tablacultivo.getColumnModel().getColumn(3).setResizable(false);
            Tablacultivo.getColumnModel().getColumn(4).setResizable(false);
            Tablacultivo.getColumnModel().getColumn(5).setResizable(false);
            Tablacultivo.getColumnModel().getColumn(6).setResizable(false);
        }

        jTextField1.setText("Buscar");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btn_Eliminar))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(1, 1, 1)
                        .addComponent(btn_Eliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        int fila = Tablacultivo.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cultivo para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) Tablacultivo.getModel();
        Object idObj = modelo.getValueAt(fila, 0);
        int id;
        try {
            id = Integer.parseInt(String.valueOf(idObj));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Confirma eliminar el cultivo seleccionado?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (opcion != JOptionPane.YES_OPTION) return;

        boolean ok = controlador.eliminarCultivo(id);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Cultivo eliminado correctamente.");
            cargarDatosTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el cultivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
         controlador.abrirEditarCultivo();
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
   controlador.abrirAgregarCultivo();
   
    
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablacultivo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
