/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author isaac
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private javax.swing.JPanel glassPaneBlocker;
    GestionProduccion ventanaProduccion;
    GestionAlmacenamiento ventanaAlmacen;
    GestionEmpleados ventanaEmpleados;
    GestionCultivo ventanaProducto;
    AyudaDialog ventanaAyuda;
    GestionDistribucion ventanaDistribucion;

    /**
     * Creates new form Gui
     */
    public MenuPrincipal() {
        initComponents();
        initializeGlassPane(); // NUEVA LLAMADA
        inicializarventanas();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public void inicializarventanas() {
        ventanaProduccion = new GestionProduccion();
        ventanaAlmacen = new GestionAlmacenamiento();
        ventanaEmpleados = new GestionEmpleados();
        ventanaProducto = new GestionCultivo();
        ventanaAyuda = new AyudaDialog(this, true);
        ventanaDistribucion = new GestionDistribucion();
    }

    private void mostrarVentana(javax.swing.JInternalFrame ventana) {
        if (ventana.getParent() == null) {
            jDesktopPane.add(ventana);
        }
        ventana.setVisible(true);
        try {
            ventana.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
    }

    private void initializeGlassPane() {
        glassPaneBlocker = new javax.swing.JPanel();
        glassPaneBlocker.setOpaque(false);
        glassPaneBlocker.addMouseListener(new java.awt.event.MouseAdapter() {
        });
        glassPaneBlocker.addKeyListener(new java.awt.event.KeyAdapter() {
        });
        glassPaneBlocker.setVisible(false);
        this.setGlassPane(glassPaneBlocker);
    }

    public void mostrarVentanaLogin() {

        glassPaneBlocker.setVisible(true);

        IniciarSession loginDialog = new IniciarSession(this, false);

        loginDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (glassPaneBlocker != null) {
                    glassPaneBlocker.setVisible(false);
                }
            }
        });

        loginDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmenuAgricola = new javax.swing.JMenu();
        jmenuProduccion = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuproducto = new javax.swing.JMenuItem();
        jMenuAlmacenes = new javax.swing.JMenuItem();
        jMenuDistribuccion = new javax.swing.JMenuItem();
        cerrarSession = new javax.swing.JMenuItem();
        Empleados = new javax.swing.JMenu();
        jMenuEmpleado = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu2.setText("jMenu2");

        jMenuItem7.setText("jMenuItem7");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        JmenuAgricola.setText("Gestión Agricola");

        jmenuProduccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmenuProduccion.setText("Producion");
        jmenuProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuProduccionActionPerformed(evt);
            }
        });
        JmenuAgricola.add(jmenuProduccion);

        jMenu1.setText("Almacenamiento");

        jMenuproducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuproducto.setText("Cultivo/Producto");
        jMenuproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuproductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuproducto);

        jMenuAlmacenes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuAlmacenes.setText("Almacenes");
        jMenuAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlmacenesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAlmacenes);

        JmenuAgricola.add(jMenu1);

        jMenuDistribuccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuDistribuccion.setText("Distribuccion");
        jMenuDistribuccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDistribuccionActionPerformed(evt);
            }
        });
        JmenuAgricola.add(jMenuDistribuccion);

        cerrarSession.setText("Cerrar Session");
        cerrarSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSessionActionPerformed(evt);
            }
        });
        JmenuAgricola.add(cerrarSession);

        jMenuBar1.add(JmenuAgricola);

        Empleados.setText("Administracion");

        jMenuEmpleado.setText("Empleados");
        jMenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpleadoActionPerformed(evt);
            }
        });
        Empleados.add(jMenuEmpleado);

        jMenuBar1.add(Empleados);

        Ayuda.setText("Ayuda");

        jMenuItem5.setText("Guia de uso");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Ayuda.add(jMenuItem5);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDistribuccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDistribuccionActionPerformed
        // TODO add your handling code here:
        mostrarVentana(ventanaDistribucion);

    }//GEN-LAST:event_jMenuDistribuccionActionPerformed

    private void jmenuProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuProduccionActionPerformed

        mostrarVentana(ventanaProduccion);

    }//GEN-LAST:event_jmenuProduccionActionPerformed

    private void jMenuproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuproductoActionPerformed
        // TODO add your handling code here:
        mostrarVentana(ventanaProducto);

    }//GEN-LAST:event_jMenuproductoActionPerformed

    private void jMenuAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlmacenesActionPerformed

        mostrarVentana(ventanaAlmacen);

    }//GEN-LAST:event_jMenuAlmacenesActionPerformed

    private void cerrarSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSessionActionPerformed

        ventanaProduccion.dispose();
        ventanaAlmacen.dispose();
        ventanaEmpleados.dispose();
        ventanaProducto.dispose();
        ventanaDistribucion.dispose();
        mostrarVentanaLogin();

    }//GEN-LAST:event_cerrarSessionActionPerformed

    private void jMenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpleadoActionPerformed

        mostrarVentana(ventanaEmpleados);

    }//GEN-LAST:event_jMenuEmpleadoActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal principal = new MenuPrincipal();
                // ESTA LÍNEA DEBE ASEGURARSE DE CERRAR LA APP CUANDO SE CIERRE LA VENTANA PRINCIPAL
                principal.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                principal.setVisible(true);
                principal.mostrarVentanaLogin();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu Empleados;
    private javax.swing.JMenu JmenuAgricola;
    private javax.swing.JMenuItem cerrarSession;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAlmacenes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuDistribuccion;
    private javax.swing.JMenuItem jMenuEmpleado;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuproducto;
    private javax.swing.JMenuItem jmenuProduccion;
    // End of variables declaration//GEN-END:variables
}
