package Vista.AgregarJdialog;

import Controlador.ControladorBase;
import Controlador.ObservadorManager;
import Modelo.Dto.AlmacenamientoDTO;
import Modelo.Dto.CultivoDTO;
import Modelo.Dto.ProductoAlmacenadoDTO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class AgregarProductoAlmacenado extends javax.swing.JDialog {
    private final ControladorBase controladorBase = new ControladorBase();
    private Map<String, Integer> mapaAlmacenes = new HashMap<>();
    private Map<String, Integer> mapaCultivos = new HashMap<>();
    private final DateTimeFormatter fechaFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
  
    public AgregarProductoAlmacenado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombos(); // inicializa mapas y llena JComboBox
    }
    
    
    private void cargarCombos() {
        // Vaciar controles antes de llenar
        jComboNombreAlmacen.removeAllItems();
        jComboNombreCultivo.removeAllItems();
        mapaAlmacenes.clear();
        mapaCultivos.clear();
        
        try {
            // Obtener almacenes desde el controlador (usa AlmacenamientoService)
            List<AlmacenamientoDTO> almacenes = controladorBase.obtenerDatosAlmacenes();
            if (almacenes != null) {
                for (AlmacenamientoDTO a : almacenes) {
                    if (a != null && a.getNombre() != null) {
                        mapaAlmacenes.put(a.getNombre(), a.getIdAlmacen());
                        jComboNombreAlmacen.addItem(a.getNombre());
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("Error cargando almacenes en AgregarProductoAlmacenado: " + e.getMessage());
        }
        
        try {
            // Obtener cultivos desde el controlador (usa CultivoService)
            List<CultivoDTO> cultivos = controladorBase.obtenerTodosLosCultivos();
            if (cultivos != null) {
                for (CultivoDTO c : cultivos) {
                    if (c != null && c.getNombre() != null) {
                        mapaCultivos.put(c.getNombre(), c.getId());
                        jComboNombreCultivo.addItem(c.getNombre());
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("Error cargando cultivos en AgregarProductoAlmacenado: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboNombreCultivo = new javax.swing.JComboBox<>();
        jComboNombreAlmacen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad (Kg)");

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de cultivo");

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Fecha egreso");

        jLabel5.setText("Fecha ingreso");

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Nombre de almacen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jComboNombreCultivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jComboNombreAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboNombreCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboNombreAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        // CORRECCIÓN: addContainerGap debe estar dentro de un SequentialGroup, no directamente en ParallelGroup
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        String nombreAlmacen = (String) jComboNombreAlmacen.getSelectedItem();
        String nombreCultivo = (String) jComboNombreCultivo.getSelectedItem();
        String cantidadStr = jTextField2.getText().trim();
        String fechaIngreso = jTextField3.getText().trim(); 

        // Validaciones básicas
        if (nombreAlmacen == null || nombreAlmacen.isEmpty() ||
            nombreCultivo == null || nombreCultivo.isEmpty() ||
            cantidadStr.isEmpty() || fechaIngreso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos obligatorios.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double cantidadKg;
        try {
            cantidadKg = Double.parseDouble(cantidadStr);
            if (cantidadKg <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo.", "Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error de formato: La cantidad debe ser un número válido.", "Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar formato de fecha yyyy-MM-dd
        try {
            LocalDate.parse(fechaIngreso, fechaFormatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "La fecha de ingreso debe tener el formato YYYY-MM-DD.", "Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mapear nombres a IDs de forma segura
        int idAlmacen = mapaAlmacenes.getOrDefault(nombreAlmacen, -1);
        int idCultivo = mapaCultivos.getOrDefault(nombreCultivo, -1);

        if (idAlmacen == -1) {
            JOptionPane.showMessageDialog(this, "No se encontró el almacén seleccionado.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (idCultivo == -1) {
            JOptionPane.showMessageDialog(this, "No se encontró el cultivo seleccionado.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear DTO y llamar al controlador
        try {
            ProductoAlmacenadoDTO productoDTO = new ProductoAlmacenadoDTO(
                0, 
                idAlmacen, 
                idCultivo, 
                nombreCultivo,
                cantidadKg, 
                fechaIngreso, 
                null 
            );

            if (controladorBase.guardarProductoAlmacenado(productoDTO)) {
                JOptionPane.showMessageDialog(this, "Producto almacenado guardado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                ObservadorManager.getInstancia().notificarCambio("PRODUCTOALMACENADO"); 
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error: No se pudo guardar el producto almacenado (Validación de BD).", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // Intencionalmente vacío
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AgregarProductoAlmacenado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarProductoAlmacenado dialog = new AgregarProductoAlmacenado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            } 
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JComboBox<String> jComboNombreAlmacen;
    private javax.swing.JComboBox<String> jComboNombreCultivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}