/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.AgregarJdialog;

import Controlador.ControladorBase;
import Modelo.Dto.DistribucionDTO;
import Modelo.Dto.ProductoAlmacenadoDTO;
import Modelo.Dto.TrabajadorDTO;
import Modelo.Service.CultivoService;
import Modelo.Service.ProductoAlmacenadoService;
import Modelo.Service.TrabajadorService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class AgregarDistribucion extends javax.swing.JDialog {

    private final CultivoService cultivoService = new CultivoService();
    private final TrabajadorService trabajadorService = new TrabajadorService();
    private final ProductoAlmacenadoService productoAlmacenadoService = new ProductoAlmacenadoService(); // Servicio para productos
    private final ControladorBase ControladorBase = new ControladorBase(); // INSTANCIA DEL CONTROLADOR
    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    /**
     * Creates new form Agregar
     *
     * @param parent
     * @param modal
     */
    public AgregarDistribucion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarComboBoxes();
    }

    private void cargarComboBoxes() {
        jComboAlmacen.removeAllItems();
        jComboResponsable.removeAllItems();
        try {
            // Poblar SOLO con productos almacenados (NO añadir cultivos aquí)
            java.util.List<ProductoAlmacenadoDTO> productos = productoAlmacenadoService.obtenerTodosLosProductosAlmacenados();
            if (productos != null) {
                for (ProductoAlmacenadoDTO producto : productos) {
                    String item = producto.getIdProductoAlmacenado()
                            + ": " + producto.getNombreCultivo()
                            + " (Cant: " + producto.getCantidadKg() + " kg)";
                    jComboAlmacen.addItem(item);
                }
            }
        } catch (Exception e) {
            System.err.println("Error al cargar productos almacenados: " + e.getMessage());
        }

        try {
            java.util.List<TrabajadorDTO> trabajadores = trabajadorService.obtenerTodosLosTrabajadores();
            for (TrabajadorDTO trabajador : trabajadores) {
                // almacenar en el combo "cedula: nombre"
                if (trabajador != null) {
                    jComboResponsable.addItem(trabajador.getCedula() + ": " + trabajador.getNombre());
                }
            }
        } catch (Exception e) {
            System.err.println("Error al cargar responsables: " + e.getMessage());
        }
    }

    private int extractId(String item) {
        if (item == null || item.isEmpty()) {
            return -1;
        }
        try {
            return Integer.parseInt(item.split(":")[0].trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    // Método auxiliar para extraer el ID de un trabajador (que es un String, ej: CÉDULA)
    private String extractTrabajadorId(String item) {
        if (item == null || item.isEmpty()) {
            return null;
        }
        return item.split(":")[0].trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextDestino = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboAlmacen = new javax.swing.JComboBox<>();
        jComboResponsable = new javax.swing.JComboBox<>();
        jTextFechaDistribucion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTextDestino.setBackground(new java.awt.Color(204, 204, 204));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad (Kg)");

        jLabel2.setText("Cultivo");

        jTextCantidad.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Fecha de Distribucion");

        jLabel4.setText("Trabajador Responsable");

        jLabel5.setText("Almacen");

        jComboAlmacen.setBackground(new java.awt.Color(204, 204, 204));
        jComboAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlmacenActionPerformed(evt);
            }
        });

        jComboResponsable.setBackground(new java.awt.Color(204, 204, 204));

        jTextFechaDistribucion.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFechaDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDestino)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboAlmacen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFechaDistribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        String productoSeleccionado = (String) jComboAlmacen.getSelectedItem();
        String responsableSeleccionado = (String) jComboResponsable.getSelectedItem();
        String cantidadStr = jTextCantidad.getText().trim();
        String destino = jTextDestino.getText().trim();
        String fechaDistribucionStr = jTextFechaDistribucion.getText().trim();
        
        if (productoSeleccionado == null || responsableSeleccionado == null || cantidadStr.isEmpty() 
                || destino.isEmpty() || fechaDistribucionStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double cantidadDistribuir;
        try {
            cantidadDistribuir = Double.parseDouble(cantidadStr);
            if (cantidadDistribuir <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad a distribuir debe ser un número positivo.", "Validación", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error de formato: La cantidad debe ser un número válido.", "Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idProductoAlmacenado = extractId(productoSeleccionado);
        String cedulaResponsable = extractTrabajadorId(responsableSeleccionado);

        if (idProductoAlmacenado == -1) {
            JOptionPane.showMessageDialog(this, "Error interno: No se pudo obtener el ID del producto seleccionado.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cedulaResponsable == null) {
            JOptionPane.showMessageDialog(this, "Error interno: No se pudo obtener la cédula del responsable. Verifique el formato.", "Error Interno", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validación de fecha
        LocalDate fechaDistribucion;
        try {
            fechaDistribucion = LocalDate.parse(fechaDistribucionStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error de formato de fecha. Use el formato YYYY-MM-DD (ej. 2023-10-27).", "Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            DistribucionDTO distribucionDTO = new DistribucionDTO(
                idProductoAlmacenado, 
                cantidadDistribuir, 
                destino, 
                fechaDistribucion.toString(), 
                cedulaResponsable
            );

            if (ControladorBase.guardarDistribucion(distribucionDTO)) {
                JOptionPane.showMessageDialog(this, "Distribución agregada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                Controlador.ObservadorManager.getInstancia().notificarCambio("DISTRIBUCION"); 
                
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar la distribución. Revise si hay suficiente stock o un error de conexión.", "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error Interno", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jComboAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarDistribucion dialog = new AgregarDistribucion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> jComboAlmacen;
    private javax.swing.JComboBox<String> jComboResponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextDestino;
    private javax.swing.JTextField jTextFechaDistribucion;
    // End of variables declaration//GEN-END:variables
}
